{% set name = "paket" %}
{% set version = "9.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/fsprojects/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 4327d63efd984f15a5736f08668ab57e5927beb436ce67a223168618a4a97b19

build:
  noarch: generic
  number: 0

requirements:
  build:
    - sed
  host:
    - dotnet
    - nuget-license
  run:
    - dotnet

test:
  commands:
    - {{ name }} --help

about:
  home: https://fsprojects.github.io/Paket
  license: MIT
  license_file:
    - LICENSE.txt
    - license-files/
  summary: A dependency manager for .NET with support for NuGet packages and Git repositories
  dev_url: https://github.com/fsprojects/{{ name }}

extra:
  recipe-maintainers:
    - danielnachun
