{% set name = "paket" %}
{% set version = "9.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/fsprojects/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 42415d2592b93c1dce70e15a12c9b67619bbf08580967b97d2ba83d3b5600b58

build:
  noarch: generic
  number: 0

requirements:
  build:
    - sed
  host:
    - dotnet
    - nuget-license
  run:
    - dotnet

test:
  commands:
    - paket --help

about:
  home: https://fsprojects.github.io/Paket
  license: MIT
  license_file:
    - LICENSE.txt
    - license-files/
  summary: A dependency manager for .NET with support for NuGet packages and Git repositories
  dev_url: https://github.com/fsprojects/paket

extra:
  recipe-maintainers:
    - danielnachun
