context:
  version: 9.0.2

package:
  name: paket
  version: ${{ version }}

source:
  url: https://github.com/fsprojects/paket/archive/${{ version }}.tar.gz
  sha256: 42415d2592b93c1dce70e15a12c9b67619bbf08580967b97d2ba83d3b5600b58

build:
  number: 1
  noarch: generic

requirements:
  build:
    - sed
  host:
    - dotnet
    - nuget-license
  run:
    - dotnet

tests:
  - script:
      - paket --help

about:
  license: MIT
  license_file:
    - LICENSE.txt
    - license-files/
  summary: A dependency manager for .NET with support for NuGet packages and Git repositories
  homepage: https://fsprojects.github.io/Paket
  repository: https://github.com/fsprojects/paket

extra:
  recipe-maintainers:
    - danielnachun
